// lib/data/local/database/app_database.dart

import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';
import 'package:menahariya/data/models/user/user_model.dart';
import 'package:menahariya/data/models/trip/trip_model.dart';
import 'package:menahariya/data/models/ticket/ticket_model.dart';
import 'package:menahariya/data/models/cargo/cargo_model.dart';
import 'package:menahariya/data/models/notification/notification_model.dart';

class AppDatabase {
  static AppDatabase? _instance;
  factory AppDatabase() => _instance ??= AppDatabase._internal();
  AppDatabase._internal();

  // Box names
  static const String userBox = 'user_box';
  static const String tripBox = 'trip_box';
  static const String ticketBox = 'ticket_box';
  static const String cargoBox = 'cargo_box';
  static const String notificationBox = 'notification_box';
  static const String cacheBox = 'cache_box';
  static const String settingsBox = 'settings_box';

  // Box instances
  late Box<UserModel> userBoxInstance;
  late Box<TripModel> tripBoxInstance;
  late Box<TicketModel> ticketBoxInstance;
  late Box<CargoModel> cargoBoxInstance;
  late Box<NotificationModel> notificationBoxInstance;
  late Box<Map> cacheBoxInstance;
  late Box<Map> settingsBoxInstance;

  // Initialization flag
  bool _isInitialized = false;
  bool get isInitialized => _isInitialized;

  // Initialize Hive and register adapters
  Future<void> initialize() async {
    if (_isInitialized) return;

    try {
      // Set Hive storage directory
      final appDocumentDir = await getApplicationDocumentsDirectory();
      Hive.init(appDocumentDir.path);

      // Register adapters
      _registerAdapters();

      // Open boxes
      await Future.wait([
        _openUserBox(),
        _openTripBox(),
        _openTicketBox(),
        _openCargoBox(),
        _openNotificationBox(),
        _openCacheBox(),
        _openSettingsBox(),
      ]);

      _isInitialized = true;
      print('AppDatabase initialized successfully');
    } catch (e) {
      print('Error initializing AppDatabase: $e');
      rethrow;
    }
  }

  // Register TypeAdapters for Hive
  void _registerAdapters() {
    // Register adapters here - these will be generated by build_runner
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(TripModelAdapter());
    // Hive.registerAdapter(TicketModelAdapter());
    // Hive.registerAdapter(CargoModelAdapter());
    // Hive.registerAdapter(NotificationModelAdapter());

    // For now, using dynamic boxes
  }

  // Open individual boxes
  Future<void> _openUserBox() async {
    userBoxInstance = await Hive.openBox<UserModel>(userBox);
  }

  Future<void> _openTripBox() async {
    tripBoxInstance = await Hive.openBox<TripModel>(tripBox);
  }

  Future<void> _openTicketBox() async {
    ticketBoxInstance = await Hive.openBox<TicketModel>(ticketBox);
  }

  Future<void> _openCargoBox() async {
    cargoBoxInstance = await Hive.openBox<CargoModel>(cargoBox);
  }

  Future<void> _openNotificationBox() async {
    notificationBoxInstance = await Hive.openBox<NotificationModel>(notificationBox);
  }

  Future<void> _openCacheBox() async {
    cacheBoxInstance = await Hive.openBox<Map>(cacheBox);
  }

  Future<void> _openSettingsBox() async {
    settingsBoxInstance = await Hive.openBox<Map>(settingsBox);
  }

  // Clear all data
  Future<void> clearAllData() async {
    await Future.wait([
      userBoxInstance.clear(),
      tripBoxInstance.clear(),
      ticketBoxInstance.clear(),
      cargoBoxInstance.clear(),
      notificationBoxInstance.clear(),
      cacheBoxInstance.clear(),
      settingsBoxInstance.clear(),
    ]);
  }

  // Close all boxes
  Future<void> close() async {
    await Future.wait([
      userBoxInstance.close(),
      tripBoxInstance.close(),
      ticketBoxInstance.close(),
      cargoBoxInstance.close(),
      notificationBoxInstance.close(),
      cacheBoxInstance.close(),
      settingsBoxInstance.close(),
    ]);
  }

  // Compact database
  Future<void> compact() async {
    await Future.wait([
      userBoxInstance.compact(),
      tripBoxInstance.compact(),
      ticketBoxInstance.compact(),
      cargoBoxInstance.compact(),
      notificationBoxInstance.compact(),
      cacheBoxInstance.compact(),
      settingsBoxInstance.compact(),
    ]);
  }

  // Delete database files
  Future<void> deleteDatabase() async {
    await close();

    final appDocumentDir = await getApplicationDocumentsDirectory();
    final databasePath = appDocumentDir.path;

    // Delete all Hive files
    await Future.wait([
      Hive.deleteBoxFromDisk(userBox),
      Hive.deleteBoxFromDisk(tripBox),
      Hive.deleteBoxFromDisk(ticketBox),
      Hive.deleteBoxFromDisk(cargoBox),
      Hive.deleteBoxFromDisk(notificationBox),
      Hive.deleteBoxFromDisk(cacheBox),
      Hive.deleteBoxFromDisk(settingsBox),
    ]);

    _isInitialized = false;
  }

  // Get database statistics
  Map<String, dynamic> getStats() {
    return {
      'userBox': {
        'name': userBox,
        'size': userBoxInstance.length,
        'keys': userBoxInstance.keys.length,
      },
      'tripBox': {
        'name': tripBox,
        'size': tripBoxInstance.length,
        'keys': tripBoxInstance.keys.length,
      },
      'ticketBox': {
        'name': ticketBox,
        'size': ticketBoxInstance.length,
        'keys': ticketBoxInstance.keys.length,
      },
      'cargoBox': {
        'name': cargoBox,
        'size': cargoBoxInstance.length,
        'keys': cargoBoxInstance.keys.length,
      },
      'notificationBox': {
        'name': notificationBox,
        'size': notificationBoxInstance.length,
        'keys': notificationBoxInstance.keys.length,
      },
      'cacheBox': {
        'name': cacheBox,
        'size': cacheBoxInstance.length,
        'keys': cacheBoxInstance.keys.length,
      },
      'settingsBox': {
        'name': settingsBox,
        'size': settingsBoxInstance.length,
        'keys': settingsBoxInstance.keys.length,
      },
    };
  }
}

// Extension methods for Box operations
extension BoxExtensions<T> on Box<T> {
  // Put with expiry
  Future<void> putWithExpiry(String key, T value, {Duration? expiry}) async {
    await put(key, value);
    if (expiry != null) {
      // Store expiry in a separate box or as metadata
      final expiryBox = Hive.box<Map>('expiry_box');
      await expiryBox.put(key, {
        'expiry': DateTime.now().add(expiry).millisecondsSinceEpoch,
      });
    }
  }

  // Get with expiry check
  T? getWithExpiry(String key) {
    final value = get(key);
    if (value == null) return null;

    // Check expiry
    final expiryBox = Hive.box<Map>('expiry_box');
    final expiryData = expiryBox.get(key);
    if (expiryData != null) {
      final expiryTime = expiryData['expiry'] as int;
      if (DateTime.now().millisecondsSinceEpoch > expiryTime) {
        // Expired - remove
        delete(key);
        expiryBox.delete(key);
        return null;
      }
    }

    return value;
  }
}

// Batch operations class
class BatchOperations {
  final AppDatabase _db;

  BatchOperations(this._db);

  // Batch insert multiple items
  Future<void> insertUsers(List<UserModel> users) async {
    final box = _db.userBoxInstance;
    await box.putAll({
      for (var user in users) user.id: user,
    });
  }

  Future<void> insertTrips(List<TripModel> trips) async {
    final box = _db.tripBoxInstance;
    await box.putAll({
      for (var trip in trips) trip.id: trip,
    });
  }

  Future<void> insertTickets(List<TicketModel> tickets) async {
    final box = _db.ticketBoxInstance;
    await box.putAll({
      for (var ticket in tickets) ticket.id: ticket,
    });
  }

  // Batch delete
  Future<void> deleteUsers(List<String> userIds) async {
    final box = _db.userBoxInstance;
    await box.deleteAll(userIds);
  }

  Future<void> deleteTrips(List<String> tripIds) async {
    final box = _db.tripBoxInstance;
    await box.deleteAll(tripIds);
  }

  // Clear all except specified boxes
  Future<void> clearAllExcept({List<String>? excludeBoxes}) async {
    excludeBoxes ??= [];

    if (!excludeBoxes.contains(AppDatabase.userBox)) {
      await _db.userBoxInstance.clear();
    }
    if (!excludeBoxes.contains(AppDatabase.tripBox)) {
      await _db.tripBoxInstance.clear();
    }
    if (!excludeBoxes.contains(AppDatabase.ticketBox)) {
      await _db.ticketBoxInstance.clear();
    }
    if (!excludeBoxes.contains(AppDatabase.cargoBox)) {
      await _db.cargoBoxInstance.clear();
    }
    if (!excludeBoxes.contains(AppDatabase.notificationBox)) {
      await _db.notificationBoxInstance.clear();
    }
    if (!excludeBoxes.contains(AppDatabase.cacheBox)) {
      await _db.cacheBoxInstance.clear();
    }
  }
}